name: CI with Cache

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-5c834c2

      - name: prime-cache-5c834c2
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi

